In [11]:
import eurostat
import pandas as pd
import numpy as np
import requests, json

%load_ext autoreload
%autoreload 2

DEMOGRAPH = "demo_r_d2jan"
ENVIRONMENT = "env_air_gge"
DBS = [DEMOGRAPH, ENVIRONMENT]

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
data = eurostat.get_data_df(DEMOGRAPH)
data.to_csv("demo.csv", index=False)
data = eurostat.get_data_df(ENVIRONMENT)
data.to_csv("env.csv", index=False)

# Dimensions and label meanings

In [ ]:
for DB in DBS:
    print(DB)

    dims = eurostat.get_pars(DB)
    print(f"Dimension labels: {dims}\n")

    for dim in dims:
        print(f"{dim}'s label meanings:\n{eurostat.get_dic(DB, dim)}\n")

In [ ]:
df = eurostat.get_data_df(DEMOGRAPH)
#print(df.columns)

geo_data_demo = sorted(df["geo\\TIME_PERIOD"].unique())
geo_demo_nuts2 = sorted({g for g in geo_data_demo if len(g) == 4 and not g.endswith("ZZ") and not g.endswith("XX") and g not in {"EU28", "EFTA"}})
print(f"Demographic's NUTS2 region labels: {geo_demo_nuts2}")

df = eurostat.get_data_df(ENVIRONMENT)
#print(df.columns)

geo_data_env = sorted(df["geo\\TIME_PERIOD"].unique())
geo_env_country = sorted(set([g for g in geo_data_env if len(g) == 2]))
print(f"Environmental emission country labels: {geo_env_country}")

In [ ]:
from datetime import datetime

df = eurostat.get_data_df(DEMOGRAPH)
dim = eurostat.get_pars(DEMOGRAPH)
demo_slice = df[(df["age"] == "TOTAL")
                & (df["sex"] == "T")
                & (df["geo\\TIME_PERIOD"].isin(geo_demo_nuts2))]
demo_vals = demo_slice[demo_slice.columns[len(dim):]]
print(f"Demographic's value range: {demo_vals.min().min()}, {demo_vals.max().max()}")

df_env = eurostat.get_data_df(ENVIRONMENT)
dim_env = eurostat.get_pars(ENVIRONMENT)
AGG = {"EU27_2020", "EU28", "EA19", "EA20"}
env_slice = df_env[(df_env["airpol"] == "GHG")
                   & (df_env["src_crf"] == "TOTX4_MEMO")
                   & (df_env["geo\\TIME_PERIOD"].isin(geo_env_country))]
env_vals = env_slice[env_slice.columns[len(dim_env):]]
print(f"Environmental emission value range: {env_vals.min().min()}, {env_vals.max().max()}")

print(f"Demographic's data staleness: {datetime.now().year - int(demo_slice.columns[len(dim):].max())} year(s)")
print(f"Environmental emission data staleness: {datetime.now().year - int(env_slice.columns[len(dim_env):].max())} year(s)")

Demographic's value range: 0.0, 15907951.0
Environmental emission value range: 1.83974, 1253127.92
Demographic's data staleness: 1 year(s)
Environmental emission data staleness: 2 year(s)

In [ ]:
BASE = "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data"
resp = requests.get(f"{BASE}/demo_r_d2jan",
    params={"format":"JSON","lang":"en","age":"TOTAL","sex":"T"},
    timeout=30)
resp.raise_for_status()
d = resp.json()
print(json.dumps(d, indent=2))
# print(d["value"])
# print(d["dimension"]["time"]["category"]["index"])

In [ ]:
# keys = np.array([36])
# np.unravel_index(keys, [1,1,1,1,521,36])
# # -> (array([0,0,0]), ..., array([0,1,468]), array([0,0,0]))
# print(36//521)
# print(521//36)
# print(36%521)
# print(521%36)

resp = requests.get(f"https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/env_air_gge",
    params={"format":"JSON", "lang":"en"},
    timeout=30)
resp.raise_for_status()
d = resp.json()
print(json.dumps(d, indent=2))

keys = np.array([int(k) for k in d["value"].keys()])
print(keys)
inds = np.unravel_index(keys, d["size"])
print(inds)

cols = {}
for name, ind in zip(d["id"], inds):
    inv = {int(v): k for k, v in d["dimension"][name]["category"]["index"].items()}
    cols[name] = [inv[i] for i in ind]
cols["value"] = [float(v) for v in d["value"].values()]

data = pd.DataFrame(cols)
data.head()

# freq_inv = {int(v): k for k, v in d["dimension"]["freq"]["category"]["index"].items()}
# unit_inv = {int(v): k for k, v in d["dimension"]["unit"]["category"]["index"].items()}
# sex_inv = {int(v): k for k, v in d["dimension"]["sex"]["category"]["index"].items()}
# age_inv = {int(v): k for k, v in d["dimension"]["age"]["category"]["index"].items()}
# geo_inv = {int(v): k for k, v in d["dimension"]["geo"]["category"]["index"].items()}
# time_inv = {int(v): k for k, v in d["dimension"]["time"]["category"]["index"].items()}

In [17]:
from eurostat_dq.ingest import fetch_dataset_json
from eurostat_dq.config import DATASETS

df = fetch_dataset_json("env_air_gge", use_cache=True)
df = fetch_dataset_json("demo_r_d2jan", geo="HU11", sex="T", age="TOTAL")
df.shape
df.head()

DataFrame found in cache
DataFrame acquired from the internet
DataFrame saved to cache

  freq unit sex    age   geo  time      value
0    A   NR   T  TOTAL  HU11  2001  1759209.0
1    A   NR   T  TOTAL  HU11  2002  1739569.0
2    A   NR   T  TOTAL  HU11  2003  1719342.0
3    A   NR   T  TOTAL  HU11  2004  1705309.0
4    A   NR   T  TOTAL  HU11  2005  1697343.0

In [32]:
from eurostat_dq.ingest import fetch_dataset
from eurostat_dq.config import DATASETS
import numpy as np

df = fetch_dataset("demo_r_d2jan", use_cache=True)
df = df.rename(columns={"geo\\TIME_PERIOD":"geo"})

cols = list(df.columns)
base_dims = [dim for dim in cols if not str(dim).isdigit()]

df_long = (df.melt(id_vars=base_dims, var_name="time", value_name="value").dropna(subset=["value"]))
df_long["time"] = df_long["time"].astype(int)

print(df.shape)
print(df.head(20))

df_long.shape
df_long.head()

DataFrame found in cache
['freq', 'unit', 'sex', 'age', 'geo', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']
[]
['freq', 'unit', 'sex', 'age', 'geo']
(160800, 41)
   freq unit sex    age   geo       1990       1991       1992       1993  \
0     A   NR   F  TOTAL    AL        NaN        NaN        NaN        NaN
1     A   NR   F  TOTAL   AL0        NaN        NaN        NaN        NaN
2     A   NR   F  TOTAL  AL01        NaN        NaN        NaN        NaN
3     A   NR   F  TOTAL  AL02        NaN        NaN        NaN        NaN
4     A   NR   F  TOTAL  AL03        NaN        NaN        NaN        NaN
5     A   NR   F  TOTAL   ALX        NaN        NaN        NaN        NaN
6     A   NR   F  TOTAL  ALXX        NaN        NaN        NaN        NaN
7     A   NR   F  TOTAL    AT  3989903.0  4014682.0  4052348.0  4089274.0
8     A   NR   F  TOTAL   AT1  1700829.0  1710008.0  1725294.0  1739459.0
9     A   NR   F  TOTAL  AT11   139775.0   140071.0   141157.0   141706.0
10    A   NR   F  TOTAL  AT12   752424.0   758595.0   765016.0   772563.0
11    A   NR   F  TOTAL  AT13   808630.0   811342.0   819121.0   825190.0
12    A   NR   F  TOTAL   AT2   889103.0   890277.0   894671.0   900286.0
13    A   NR   F  TOTAL  AT21   281917.0   283082.0   285421.0   288272.0
14    A   NR   F  TOTAL  AT22   607186.0   607195.0   609250.0   612014.0
15    A   NR   F  TOTAL   AT3  1399971.0  1414397.0  1432383.0  1449529.0
16    A   NR   F  TOTAL  AT31   670153.0   675668.0   683873.0   691529.0
17    A   NR   F  TOTAL  AT32   246020.0   250219.0   253624.0   258024.0
18    A   NR   F  TOTAL  AT33   318816.0   321350.0   325329.0   328948.0
19    A   NR   F  TOTAL  AT34   164982.0   167160.0   169557.0   171028.0

         1994  ...       2016       2017       2018       2019       2020  \
0         NaN  ...  1417141.0  1423050.0  1431715.0  1432833.0  1425342.0
1         NaN  ...  1417141.0  1423050.0  1431715.0  1432833.0  1425342.0
2         NaN  ...   406682.0   405835.0   405598.0   404201.0   399599.0
3         NaN  ...   564402.0   574010.0   585530.0   590623.0   594008.0
4         NaN  ...   446057.0   443205.0   440587.0   438009.0   431735.0
5         NaN  ...        NaN        NaN        0.0        0.0        NaN
6         NaN  ...        NaN        NaN        0.0        0.0        NaN
7   4107857.0  ...  4427918.0  4460424.0  4483749.0  4501742.0  4522292.0
8   1747041.0  ...  1934748.0  1952123.0  1964998.0  1973619.0  1984110.0
9    141890.0  ...   148052.0   148416.0   149016.0   149487.0   150097.0
10   775697.0  ...   839555.0   845249.0   847971.0   851644.0   855113.0
11   829454.0  ...   947141.0   958458.0   968011.0   972488.0   978900.0
12   901119.0  ...   911819.0   914535.0   915571.0   916674.0   918428.0
13   288999.0  ...   287033.0   287516.0   287410.0   287455.0   287605.0
14   612120.0  ...   624786.0   627019.0   628161.0   629219.0   630823.0
15  1459697.0  ...  1581351.0  1593766.0  1603180.0  1611449.0  1619754.0
16   695867.0  ...   733791.0   738861.0   742757.0   746696.0   750465.0
17   260321.0  ...   278648.0   280536.0   282253.0   283641.0   285243.0
18   331687.0  ...   375090.0   378448.0   380734.0   382570.0   384035.0
19   171822.0  ...   193822.0   195921.0   197436.0   198542.0   200011.0

         2021       2022       2023       2024       2025
0   1419759.0  1406532.0  1394864.0        NaN  1194597.0
1   1419759.0  1406532.0  1394864.0        NaN  1194597.0
2    396799.0   390886.0   385462.0        NaN   317141.0
3    596005.0   597622.0   598531.0        NaN   506383.0
4    426955.0   418024.0   410871.0        NaN   371073.0
5         NaN        NaN        NaN        NaN        NaN
6         NaN        NaN        NaN        NaN        NaN
7   4535712.0  4553444.0  4619957.0  4643918.0  4664333.0
8   1991992.0  2000081.0  2039851.0  2052543.0  2065600.0
9    150724.0   151557.0   153737.0   154169.0   154174.0
10   858326.0   861800.0   873142.0   875525.0   877327.0
11   982942.0   986724.0  1012972.0  1022849.0  1034099.0
12   918549.0   921374.0   930196.0   933159.0   934826.0
13   287622.0   288500.0   290513.0   291176.0   291416.0
14   630927.0   632874.0   639683.0   641983.0   643410.0
15  1625171.0  1631989.0  1649910.0  1658216.0  1663907.0
16   752853.0   756361.0   764882.0   767911.0   771102.0
17   286359.0   287209.0   290156.0   291635.0   292359.0
18   385077.0   386627.0   390667.0   392833.0   393658.0
19   200882.0   201792.0   204205.0   205837.0   206788.0

[20 rows x 41 columns]

   freq unit sex    age   geo  time      value
7     A   NR   F  TOTAL    AT  1990  3989903.0
8     A   NR   F  TOTAL   AT1  1990  1700829.0
9     A   NR   F  TOTAL  AT11  1990   139775.0
10    A   NR   F  TOTAL  AT12  1990   752424.0
11    A   NR   F  TOTAL  AT13  1990   808630.0

In [12]:
from eurostat_dq.ingest import fetch_dataset, fetch_dataset_json
from eurostat_dq.clean import to_tidy, apply_slice
from eurostat_dq.config import DATASETS

print("FETCH:")
for code, cfg in DATASETS.items():
    raw   = fetch_dataset(code, use_cache=False)
    tidy  = to_tidy(raw)
    clean = apply_slice(tidy, cfg)
    print(code, clean.head)

print("FETCH JSON:")
for code, cfg in DATASETS.items():
    raw   = fetch_dataset_json(code, use_cache=False)
    tidy  = to_tidy(raw)
    clean = apply_slice(tidy, cfg)
    print(code, clean.head())

FETCH:
DataFrame acquired from the internet
DataFrame saved to cache
demo_r_d2jan <bound method NDFrame.head of         freq unit sex    age   geo  time      value
107209     A   NR   T  TOTAL  AT11  1990   270670.0
107210     A   NR   T  TOTAL  AT12  1990  1455968.0
107211     A   NR   T  TOTAL  AT13  1990  1492636.0
107213     A   NR   T  TOTAL  AT21  1990   544983.0
107214     A   NR   T  TOTAL  AT22  1990  1169578.0
...      ...  ...  ..    ...   ...   ...        ...
5735661    A   NR   T  TOTAL  TRB1  2025  1724320.0
5735662    A   NR   T  TOTAL  TRB2  2025  2152387.0
5735664    A   NR   T  TOTAL  TRC1  2025  2961139.0
5735665    A   NR   T  TOTAL  TRC2  2025  4071429.0
5735666    A   NR   T  TOTAL  TRC3  2025  2457718.0

[10320 rows x 7 columns]>
DataFrame acquired from the internet
DataFrame saved to cache
env_air_gge <bound method NDFrame.head of         freq   unit airpol     src_crf geo  time         value
16487      A  MIO_T    GHG  TOTX4_MEMO  AT  1990      79.66846
42996      A  THS_T    GHG  TOTX4_MEMO  AT  1990   79668.46000
16488      A  MIO_T    GHG  TOTX4_MEMO  BE  1990     145.46665
42997      A  THS_T    GHG  TOTX4_MEMO  BE  1990  145466.65000
16489      A  MIO_T    GHG  TOTX4_MEMO  BG  1990     100.19699
...      ...    ...    ...         ...  ..   ...           ...
1845637    A  THS_T    GHG  TOTX4_MEMO  SI  2024   15483.81000
1819129    A  MIO_T    GHG  TOTX4_MEMO  SK  2024      33.91803
1845638    A  THS_T    GHG  TOTX4_MEMO  SK  2024   33918.03000
1819130    A  MIO_T    GHG  TOTX4_MEMO  TR  2024     584.52134
1845639    A  THS_T    GHG  TOTX4_MEMO  TR  2024  584521.34000

[2170 rows x 7 columns]>
FETCH JSON:
DataFrame acquired from the internet
DataFrame saved to cache
demo_r_d2jan         freq unit sex    age   geo  time      value
3114791    A   NR   T  TOTAL  AT11  1990   270670.0
3114827    A   NR   T  TOTAL  AT12  1990  1455968.0
3114863    A   NR   T  TOTAL  AT13  1990  1492636.0
3114935    A   NR   T  TOTAL  AT21  1990   544983.0
3114971    A   NR   T  TOTAL  AT22  1990  1169578.0
DataFrame acquired from the internet
DataFrame saved to cache
env_air_gge         freq   unit airpol     src_crf geo  time         value
506882     A  MIO_T    GHG  TOTX4_MEMO  AT  1990      79.66846
1342251    A  THS_T    GHG  TOTX4_MEMO  AT  1990   79668.46000
506917     A  MIO_T    GHG  TOTX4_MEMO  BE  1990     145.46665
1342286    A  THS_T    GHG  TOTX4_MEMO  BE  1990  145466.65000
506952     A  MIO_T    GHG  TOTX4_MEMO  BG  1990     100.19699

In [ ]:
print(df)

        freq unit sex     age   geo  time      value
0          A   NR   F   TOTAL    AL  2000  1526762.0
1          A   NR   F   TOTAL    AL  2001  1535822.0
2          A   NR   F   TOTAL    AL  2002  1532563.0
3          A   NR   F   TOTAL    AL  2003  1526180.0
4          A   NR   F   TOTAL    AL  2004  1520481.0
...      ...  ...  ..     ...   ...   ...        ...
4671906    A   NR   T  Y_OPEN  UKN0  2014      250.0
4671907    A   NR   T  Y_OPEN  UKN0  2015      265.0
4671908    A   NR   T  Y_OPEN  UKN0  2016      274.0
4671909    A   NR   T  Y_OPEN  UKN0  2017      281.0
4671910    A   NR   T  Y_OPEN  UKN0  2018      282.0

[4671911 rows x 7 columns]
        freq   unit    airpol   src_crf geo  time      value
0          A  MIO_T       CH4      CRF1  AT  1990    0.05442
1          A  MIO_T       CH4      CRF1  AT  1991    0.04970
2          A  MIO_T       CH4      CRF1  AT  1992    0.04877
3          A  MIO_T       CH4      CRF1  AT  1993    0.04635
4          A  MIO_T       CH4      CRF1  AT  1994    0.03954
...      ...    ...       ...       ...  ..   ...        ...
1670733    A  THS_T  SF6_CO2E  TOTXMEMO  TR  2020  174.84000
1670734    A  THS_T  SF6_CO2E  TOTXMEMO  TR  2021  182.17000
1670735    A  THS_T  SF6_CO2E  TOTXMEMO  TR  2022  208.35000
1670736    A  THS_T  SF6_CO2E  TOTXMEMO  TR  2023  195.47000
1670737    A  THS_T  SF6_CO2E  TOTXMEMO  TR  2024  184.43000

[1670738 rows x 7 columns]

In [51]:
from eurostat_dq.config import DATASETS, PROJECT_ROOT
from eurostat_dq.ingest import fetch_dataset
from eurostat_dq.clean import to_tidy

df = fetch_dataset(ENVIRONMENT, use_cache=True)
df = to_tidy(df)

filters = DATASETS[ENVIRONMENT].filters
geo_level = DATASETS[ENVIRONMENT].geo_level.lower()

geo_data = sorted(df["geo"].unique())
geo_data_leveled = []

if geo_level == "nuts2":
    geo_data_leveled = sorted({g for g in geo_data if len(g) == 4 and not g.endswith(("ZZ", "XX")) and not g.startswith(("EU", "EA")) and not g.isalpha()})
    print(f"Data of NUTS2 region labels: {geo_data_leveled}")
elif geo_level == "country":
    geo_data_leveled = sorted(set([g for g in geo_data if len(g) == 2]))
    print(f"Data of Country labels: {geo_data_leveled}")

mask = pd.Series(True, index=df.index)
mask &= df["geo"].isin(geo_data_leveled)
for col, val in filters.items():
    mask &= df[col] == val
df = df[mask]
cache_path = PROJECT_ROOT / "data" / "processed" / f"{ENVIRONMENT}.parquet"
cache_path.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(cache_path, index=False)
df.shape
df.head()

# print("DATA:")
# for i in {"EU27_2020", "EU28", "EA19", "EA20"}:
#     print(i)
#     print(df[df["geo"] == i].head(1))

DataFrame found in cache
Data of Country labels: ['AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'EL', 'ES', 'FI', 'FR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LT', 'LU', 'LV', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'TR']

      freq   unit airpol     src_crf geo  time      value
16487    A  MIO_T    GHG  TOTX4_MEMO  AT  1990   79.66846
16488    A  MIO_T    GHG  TOTX4_MEMO  BE  1990  145.46665
16489    A  MIO_T    GHG  TOTX4_MEMO  BG  1990  100.19699
16490    A  MIO_T    GHG  TOTX4_MEMO  CH  1990   55.16536
16491    A  MIO_T    GHG  TOTX4_MEMO  CY  1990    5.57948